# fly.toml app configuration file generated for grubdash-api on 2025-09-16T13:30:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grubdash-api'
primary_region = 'dfw'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
